-- AlterTable Teacher
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "hourlyRate" DOUBLE PRECISION;
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "salaryType" "SalaryType" NOT NULL DEFAULT 'PERCENT';
ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- AlterTable Student
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "studentCode" TEXT;
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- AlterTable Class
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "roomId2" TEXT;
ALTER TABLE "Class" ADD COLUMN IF NOT EXISTS "scheduleTime2" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Student_studentCode_key" ON "Student"("studentCode");
